version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: coaching
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ilovepostgress
      POSTGRES_HOST_AUTH_METHOD: password
    ports: 
      - "5432:5432"
  #   volumes:
  #   #  - ./init_scripts:/docker-entrypoint-initdb.d
  web:
    build: .
    command: ["streamlit", "run", "main.py", "--server.port", "8080"]
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    depends_on:
      - db
    environment:
      DATABASE_PORT: 5432
      DATABASE_NAME: coaching
      DATABASE_HOSTNAME: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: ilovepostgress
